<div><a href="<?php echo $this->url(array("module" => "admin", "controller" => "nhombaiviet", "action" => "add"), null, true) ?>" class="btn btn-primary">Add</a> </div>
<div class="title-action"><h2> Danh sách nhóm bài viết</h2>
</div>

<?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>

<?php if ($flashMessenger->hasMessages('delete-false')): ?>
    <div class="message success">
        <?php foreach ($flashMessenger->getMessages('delete-false') as $msg): ?>
            <div class="info-box bg-yellow">
                <span class="info-box-icon"><i class="fa fa-exclamation-triangle"></i></span>
                <div class="info-box-content">
                    <p><?php echo $msg; ?></p>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<?php if ($flashMessenger->hasMessages('delete-successful')): ?>
    <div class="message success">
        <?php foreach ($flashMessenger->getMessages('delete-successful') as $msg): ?>
            <div class="info-box bg-green">
                <span class="info-box-icon"><i class="fa fa-thumbs-o-up"></i></span>
                <div class="info-box-content">
                    <p><?php echo $msg; ?></p>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>



<?php if ($this->noRecord != NULL) : ?>
    <div class="info-box bg-yellow">
        <span class="info-box-icon"><i class="fa fa-exclamation-triangle"></i></span>
        <div class="info-box-content">
            <p>Hiện tại chưa tồn tại  <b> nhóm bài viết</b> nào!</p>
        </div><!-- /.info-box-content -->
    </div>
    <?php
    return;
endif;
?>

<div class="div-content100">
    <table class="table table-hover text-center">
        <tr class="first-tr">
            <td>Id</td>
            <td>Tên nhóm bài viết</td>
            <td>Danh mục cha</td>
            <td>Hành động</td>
        </tr>
        <?php
        foreach ($this->paginator as $nhomBaiViet) :
            $idNhomBaiViet = $nhomBaiViet['idnhom_bai_viet'];
            $tenNhomBaiViet = $nhomBaiViet['ten_nhom_bai_viet'];
            $parent = $nhomBaiViet['parent'];
            if ($parent == 0) {
                $nameParent = "Default";
            } else {
                $nameParent = $this->arrayParent[$parent];
            }
            ?>
            <tr>
                <td><?php echo $idNhomBaiViet; ?></td>
                <td><?php echo $tenNhomBaiViet; ?></td>
                <td style="text-align: left;"><?php echo $nameParent; ?></td>
                <td>
                    <a class="btn btn-warning" href="<?php echo $this->url(array("module" => "admin", "controller" => "nhombaiviet", "action" => "edit", "file" => $idNhomBaiViet), null, true); ?>"><i class="fa fa-pencil"></i> Edit</a> 
                    <a class="btn btn-danger delete-record" data-name="<?php echo $tenNhomBaiViet; ?>" href="<?php echo $this->url(array("module" => "admin", "controller" => "nhombaiviet", "action" => "delete", "file" => $idNhomBaiViet), null, true); ?>"><i class="fa fa-trash-o"></i> Del</a> 
                   
                </td>
            </tr>
        <?php endforeach; ?>

    </table>
    <?php echo $this->paginationControl($this->readall, 'Elastic', 'pagination.phtml'); ?>

</div>