<div class="clear-float">
    <div class="row text-middle border-butom">
        <div class="col-sm-2 col-xs-5">   
            <?php
            $arrayOptionsLinkAdd = array("module" => "admin",
                "controller" => "nhombaiviet",
                "action" => "add");
            $linkAdd = $this->url($arrayOptionsLinkAdd, null, true);
            ?>
            <a href="<?php echo $linkAdd; ?>" class="btn btn-primary">Add</a> </div>
        <div class="col-sm-7 col-xs-12"> <p class="title-action"> Danh sách nhóm bài viết</p></div>
        <div class="col-sm-3 col-xs-12"> 

            <form method="GET">
                <input name="search"type="text" placeholder="Search...">
            </form>
        </div>
    </div>
</div>

    <?php
    echo $this->flashMessenger();

    $noRecord = $this->noRecord;
    if ($this->noRecord($noRecord)) {
        echo $this->noRecord($noRecord);
        return;
    }
    ?>

    <div class="table-responsive">
        <table class="table table-hover text-center">
            <tr class="first-tr">
                <td>Id</td>
                <td>Tên nhóm bài viết</td>
                <td>Danh mục cha</td>
                <td>Hành động</td>
            </tr>
            <?php
            foreach ($this->paginator as $nhomBaiViet) :
                $idNhomBaiViet = $nhomBaiViet['idnhom_bai_viet'];
                $tenNhomBaiViet = $nhomBaiViet['ten_nhom_bai_viet'];
                $parent = $nhomBaiViet['parent'];
                if ($parent == 0) {
                    $nameParent = "Default";
                } else {
                    $nameParent = $this->arrayParent[$parent];
                }
                ?>
                <tr>
                    <td class="text-middle"><?php echo $idNhomBaiViet; ?></td>
                    <td class="text-overflow text-middle"><?php echo $tenNhomBaiViet; ?></td>
                    <td style="text-align: left;" class="text-overflow text-middle"><?php echo $nameParent; ?></td>
                    <td class="text-middle">
                        <a class="btn btn-default" href="<?php echo $this->url(array("module" => "admin", "controller" => "nhombaiviet", "action" => "edit", "file" => $idNhomBaiViet), null, true); ?>"><i class="fa fa-pencil"></i> Edit</a> &nbsp;&nbsp;
                        <a class="btn btn-default delete-record" data-name="<?php echo $tenNhomBaiViet; ?>" href="<?php echo $this->url(array("module" => "admin", "controller" => "nhombaiviet", "action" => "delete", "file" => $idNhomBaiViet), null, true); ?>"><i class="fa fa-trash-o"></i> Del</a> 

                    </td>
                </tr>
            <?php endforeach; ?>

        </table>

        <?php echo $this->paginationControl(NULL, 'Elastic', 'pagination.phtml'); ?>

    </div>