
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"><html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
<meta http-equiv="Refresh" content="3600" >
<meta name="keywords" content="Zend, Framework, training, course" >
<meta name="description" content="Zend Framework training course" ><title>Danh sách nhóm bài viết</title><link href="public/templates/admin/system/bootstrap/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" >
<link href="public/templates/admin/system/css/font-awesome.min.css" media="screen" rel="stylesheet" type="text/css" >
<link href="public/templates/admin/system/dist/css/AdminLTE.min.css" media="screen" rel="stylesheet" type="text/css" >
<link href="public/templates/admin/system/dist/css/skins/_all-skins.min.css" media="screen" rel="stylesheet" type="text/css" >
<link href="public/templates/admin/system/plugins/iCheck/flat/blue.css" media="screen" rel="stylesheet" type="text/css" >
<link href="public/templates/admin/system/plugins/morris/morris.css" media="screen" rel="stylesheet" type="text/css" >
<link href="public/templates/admin/system/plugins/jvectormap/jquery-jvectormap-1.2.2.css" media="screen" rel="stylesheet" type="text/css" >
<link href="public/templates/admin/system/plugins/datepicker/datepicker3.css" media="screen" rel="stylesheet" type="text/css" >
<link href="public/templates/admin/system/plugins/daterangepicker/daterangepicker-bs3.css" media="screen" rel="stylesheet" type="text/css" >
<link href="public/templates/admin/system/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css" media="screen" rel="stylesheet" type="text/css" >
<link href="public/templates/admin/system/css/mystyle.css" media="screen" rel="stylesheet" type="text/css" >


        
    </head>
    <body class="skin-blue">
          <a class="delete-record"href="http://jquery.com/">jQuddddddddddddddddddddddddddddddddddddddddddddery</a>
        
        <script type="text/javascript" src="public/templates/admin/system/plugins/jQuery/jQuery-2.1.3.min.js"></script>
        <script type="text/javascript" src="public/templates/admin/system/js/myjs.js"></script>
        <script type="text/javascript" src="public/templates/admin/system/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="public/templates/admin/system/plugins/morris/morris.min.js"></script>
<script type="text/javascript" src="public/templates/admin/system/plugins/sparkline/jquery.sparkline.min.js"></script>
<script type="text/javascript" src="public/templates/admin/system/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script type="text/javascript" src="public/templates/admin/system/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<script type="text/javascript" src="public/templates/admin/system/plugins/knob/jquery.knob.js"></script>
<script type="text/javascript" src="public/templates/admin/system/plugins/daterangepicker/daterangepicker.js"></script>
<script type="text/javascript" src="public/templates/admin/system/plugins/datepicker/bootstrap-datepicker.js"></script>
<script type="text/javascript" src="public/templates/admin/system/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<script type="text/javascript" src="public/templates/admin/system/plugins/iCheck/icheck.min.js"></script>
<script type="text/javascript" src="public/templates/admin/system/plugins/slimScroll/jquery.slimscroll.min.js"></script>
<script type="text/javascript" src="public/templates/admin/system/dist/js/app.min.js"></script>
<script type="text/javascript" src="public/templates/admin/system/dist/js/pages/dashboard.js"></script>
<script type="text/javascript" src="public/templates/admin/system/dist/js/demo.js"></script>
<script type="text/javascript" src="public/templates/admin/system/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="public/templates/admin/system/js/raphael-min.js"></script>

<script type="text/javascript" src="public/templates/admin/system/js/fastclick.min.js"></script>    </body>
</html>