<div>
    <div class="float-left"> 
        <?php
        $arrayOptionsLinkAdd = array("module" => "admin",
            "controller" => "taikhoan",
            "action" => "add");
        $linkAdd = $this->url($arrayOptionsLinkAdd, null, true);
        ?>
        <a href="<?php echo $linkAdd; ?>" class="btn btn-primary">Add</a> 
    </div>
    <div class="title-action">
        <h2> Danh sách tài khoản</h2>
    </div>
</div>


<?php
echo $this->flashMessenger();

$noRecord = $this->noRecord;
if ($this->noRecord($noRecord)) {
    echo $this->noRecord($noRecord);
    return;
}
?>

<div class="table-responsive">
    <table class="table table-hover text-center">
        <tr class="first-tr">
            <td>Id</td>
            <td>Tên tài khoản</td>
            <td>Thuộc nhóm</td>
            <td>Email</td>
            <td>Hành động</td>
        </tr>
        <?php
        foreach ($this->paginator as $taiKhoan) :
            $idTaiKhoan = $taiKhoan['idtai_khoan'];
            $tenDangNhap = $taiKhoan['ten_dang_nhap'];
            $thuocNhom = $taiKhoan['ten_nhom_tai_khoan'];
            $email = $taiKhoan['email'];
            ?>
            <tr>
                <td class="text-middle"><?php echo $idTaiKhoan; ?></td>
                <td class="text-overflow text-middle"><?php echo $tenDangNhap; ?></td>
                <td class="text-overflow text-middle"><?php echo $thuocNhom; ?></td>
                <td class="text-overflow text-middle"><?php echo $email; ?></td>
                <td class="text-middle">
                    <?php
                    $linkEdit = $this->url(array("module" => "admin",
                        "controller" => "taikhoan",
                        "action" => "edit",
                        "file" => $idTaiKhoan), null, true);
                    ?>
                    <a class="btn btn-default" href="<?php echo $linkEdit; ?>">
                        <i class="fa fa-pencil"></i> 
                        Edit
                    </a> 

                    &nbsp;&nbsp;

                    <?php
                    $linkDelete = $this->url(array("module" => "admin",
                        "controller" => "taikhoan",
                        "action" => "delete",
                        "file" => $idTaiKhoan), null, true)
                    ?>
                    <a class="btn btn-default delete-record" data-name="<?php echo $tenDangNhap; ?>" href="<?php echo $linkDelete; ?>">
                        <i class="fa fa-trash-o"></i> 
                        Del
                    </a>   

                </td>
            </tr>
<?php endforeach; ?>

    </table>

<?php echo $this->paginationControl(NULL, 'Elastic', 'pagination.phtml'); ?>

</div>