<div class="clear-float">
    <div class="row text-middle border-butom">
        <div class="col-sm-2 col-xs-5">   
            <?php
            $arrayOptionsLinkAdd = array("module" => "admin",
                "controller" => "baiviet",
                "action" => "add");
            $linkAdd = $this->url($arrayOptionsLinkAdd, null, true);
            ?>
            <a href="<?php echo $linkAdd; ?>" class="btn btn-primary">Add</a> </div>
        <div class="col-sm-7 col-xs-12"> <p class="title-action"> Danh sách bài viết</p></div>
        <div class="col-sm-3 col-xs-12"> 
            
            <form method="GET">
                <input name="search"type="text" placeholder="Search...">
            </form>
        </div>
    </div>
</div>


    <?php
    echo $this->flashMessenger();

    $noRecord = $this->noRecord;
    if ($this->noRecord($noRecord)) {
        echo $this->noRecord($noRecord);
        return;
    }
    ?>

    <div class="table-responsive clear-float">
        <table class="table table-hover text-center">
            <tr class="first-tr">
                <td>Id</td>
                <td>Tiêu đề</td>
                <td>Chuyên mục</td>
                <td>Thời gian</td>
                <td>Hành động</td>
            </tr>
            <?php
            foreach ($this->paginator as $baiviet) :
                $idBaiViet = $baiviet['idbai_viet'];
                $tieuDeBaiViet = $baiviet['tieu_de'];
                $tenNhomBaiViet = $baiviet['ten_nhom_bai_viet'];
                $thoiGian = $baiviet['thoi_gian'];
                ?>
                <tr>
                    <td class="text-middle"><?php echo $idBaiViet; ?></td>
                    <td class="text-overflow text-middle"><?php echo $tieuDeBaiViet; ?></td>
                    <td  class="text-overflow text-middle"><?php echo $tenNhomBaiViet; ?></td>
                    <td class="text-overflow text-middle"><?php echo $thoiGian; ?></td>
                    <td class="text-middle">
                        <?php
                        $linkEdit = $this->url(array("module" => "admin",
                            "controller" => "baiviet",
                            "action" => "edit",
                            "file" => $idBaiViet), null, true);
                        ?>
                        <a class="btn btn-default" href="<?php echo $linkEdit; ?>">
                            <i class="fa fa-pencil"></i> 
                            Edit
                        </a> 

                        &nbsp;&nbsp;

                        <?php
                        $linkDelete = $this->url(array("module" => "admin",
                            "controller" => "baiviet",
                            "action" => "delete",
                            "file" => $idBaiViet), null, true)
                        ?>
                        <a class="btn btn-default delete-record" data-name="<?php echo $tieuDeBaiViet; ?>" href="<?php echo $linkDelete; ?>">
                            <i class="fa fa-trash-o"></i> 
                            Del
                        </a>   

                    </td>
                </tr>
            <?php endforeach; ?>

        </table>

        <?php echo $this->paginationControl(NULL, 'Elastic', 'pagination.phtml'); ?>

    </div>
