<div class="title-action line-buttom">
    <?php
    $sessionCart = new Zend_Session_Namespace('cart');
    $listCart = $sessionCart->cart;
    ?>
    Đơn hàng
</div>
<?php if(isset($listCart)) : ?>
<table class="table table-hover line-buttom">
    <?php foreach ($listCart as $keySanPham => $valSanPham): ?>
        <?php foreach ($valSanPham as $keyMauSac => $valMauSac): ?>
            <?php foreach ($valMauSac as $keysize => $valsize): ?>
                <tr>
                    <td><?php echo $keySanPham; ?></td>
                    <td><?php echo $keyMauSac; ?></td>
                    <td><?php echo $valsize['kich_thuoc_id'] . "---" . $valsize['so_luong'] ?></td>
                </tr>
            <?php endforeach; ?>
        <?php endforeach; ?>
    <?php endforeach; ?>
    <?php
    ?>
</table>
<?php endif; ?>
<form action="" method="POST">
    <button value="Submit" name="submit" class="btn btn-primary">Nhập hàng vào kho</button>
</form>