<div class="title-action line-buttom">
    <?php
    $sessionCart = new Zend_Session_Namespace('cart');
    $listCart = $sessionCart->cart;
    ?>
    Chi tiết đơn hàng
</div>
<?php
?>
<?php if (!isset($listCart)): ?>
    <div class="line-buttom"> Hiện tại đơn hàng trống</div>
<?php endif; ?>
<?php if (isset($listCart)) : ?>
    <table class="table table-hover line-buttom">
        <tr class="first-tr">
            <td class="text-center"> Tên sản phẩm</td>  
            <td class="text-center"> Mầu sắc</td>
            <td class="text-center"> Kích cỡ</td>  
            <td class="text-center">Số lượng</td>  
        </tr>
        <?php foreach ($listCart as $keySanPham => $valSanPham): ?>
            <?php foreach ($valSanPham as $keyMauSac => $valMauSac): ?>
                <?php foreach ($valMauSac as $keysize => $valsize): ?>
                    <tr>
                        <td class="text-center"><?php echo $this->mapIdToNameSanPham[$keySanPham]; ?></td>
                        <td class="text-center"><?php echo $this->mapIdToNameMauSac[$keyMauSac]; ?></td>
                        <td class="text-center"><?php echo $this->mapIdToNameKichThuoc[$valsize['kich_thuoc_id']]; ?></td> 
                        <td class="text-center"><?php echo $valsize['so_luong']; ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php endforeach; ?>
        <?php endforeach; ?>
        <tr>
            <td colspan="4"> <a href="<?php echo $this->url(array("module" => "admin", "controller" => "nhaphang", "action" => "addsanpham"), null, true); ?>">
                    <input class="btn btn-primary" type="button" value="Nhập sản phẩm khác" />
                </a>
                <a href="<?php echo $this->url(array("module" => "admin", "controller" => "nhaphang", "action" => "adddonhang"), null, true); ?>">
                    <input class="btn btn-primary" type="button" value="Submit đơn hàng" />
                </a>
            </td>
        </tr>


    </table>
<?php endif; ?>
<div class="title-action line-buttom">
    Nhập hàng vào kho
</div>
<?php
if ($this->formAdd) {
    $formAdd = $this->formAdd;
} else {
    return;
}
?>

<div class="div-content100">
    <form class="form-horizontal" method="POST">
        <div class="form-group">
            <label class="col-sm-1 control-label">Mầu sắc</label>
            <div class="col-sm-2">
                <?php echo $formAdd->mau_sac_id;
                ?>
            </div>

            <div class="col-sm-9">
                <?php
                $optionsKichThuoc = $formAdd->kich_thuoc_id->options;
                foreach ($optionsKichThuoc as $key => $val) :
                    ?>
                    <div class="row"> 
                        <label class="col-sm-2">Kích thước</label>
                        <div class="col-sm-3"><input type="checkbox" name="kich_thuoc_id[]" value="<?php echo $key; ?>" /><?php echo $val; ?></div>
                        <label class="col-sm-2">Số lượng</label>
                        <div class="col-sm-5"><?php echo $formAdd->so_luong->setAttrib("name", "so_luong[$key]"); ?></div>
                    </div>
                <?php endforeach; ?>

            </div>
        </div>


        <?php echo $formAdd->submit; ?>

    </form>
</div>