<div class="clear-float">
    <div class="row text-middle border-butom">
        <div class="col-sm-2 col-xs-5">   
            <?php
            $arrayOptionsLinkAdd = array("module" => "admin",
                "controller" => "tinhthanhpho",
                "action" => "add");
            $linkAdd = $this->url($arrayOptionsLinkAdd, null, true);
            ?>
            <a href="<?php echo $linkAdd; ?>" class="btn btn-primary">Add</a> </div>
        <div class="col-sm-7 col-xs-12"> <p class="title-action"> Danh sách tỉnh thành phố</p></div>
        <div class="col-sm-3 col-xs-12"> 

            <form method="GET">
                <input name="search"type="text" placeholder="Search...">
            </form>
        </div>
    </div>
</div>


<?php
echo $this->flashMessenger();

$noRecord = $this->noRecord;
if ($this->noRecord($noRecord)) {
    echo $this->noRecord($noRecord);
    return;
}
?>

<div class="table-responsive">
    <table class="table table-hover text-center">
        <tr class="first-tr">
            <td>Id</td>
            <td>Tên tỉnh thành phố</td>
            <td>Hành động</td>
        </tr>
        <?php
        foreach ($this->paginator as $tinhThanhPho) :
            $idTinhThanhPho = $tinhThanhPho['idtinh_thanh_pho'];
            $tenTinhThanhPho = $tinhThanhPho['ten_tinh_thanh_pho'];
            ?>
            <tr>
                <td class="text-middle"><?php echo $idTinhThanhPho; ?></td>
                <td class="text-overflow text-middle"><?php echo $tenTinhThanhPho; ?></td>
                <td class="text-middle">
                    <a class="btn btn-default" href="<?php echo $this->url(array("module" => "admin", "controller" => "tinhthanhpho", "action" => "edit", "file" => $idTinhThanhPho), null, true); ?>"><i class="fa fa-pencil"></i> Edit</a> &nbsp;&nbsp;
                    <a class="btn btn-default delete-record" data-name="<?php echo $tenTinhThanhPho; ?>" href="<?php echo $this->url(array("module" => "admin", "controller" => "tinhthanhpho", "action" => "delete", "file" => $idTinhThanhPho), null, true); ?>"><i class="fa fa-trash-o"></i> Del</a> 

                </td>
            </tr>
        <?php endforeach; ?>

    </table>

    <?php echo $this->paginationControl(NULL, 'Elastic', 'pagination.phtml'); ?>

</div>