<?php

echo $this->headScript()->appendFile(TEMPLATE_URL . '/admin/system/plugins/jQuery/jQuery-2.1.3.min.js', 'text/javascript')
        ->appendFile(TEMPLATE_URL . '/admin/system/js/myjs.js', 'text/javascript')
        ->appendFile(TEMPLATE_URL . '/admin/system/bootstrap/js/bootstrap.min.js', 'text/javascript')
        ->appendFile(TEMPLATE_URL . '/admin/system/plugins/morris/morris.min.js', 'text/javascript')
        ->appendFile(TEMPLATE_URL . '/admin/system/plugins/sparkline/jquery.sparkline.min.js', 'text/javascript')
        ->appendFile(TEMPLATE_URL . '/admin/system/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js', 'text/javascript')
        ->appendFile(TEMPLATE_URL . '/admin/system/plugins/jvectormap/jquery-jvectormap-world-mill-en.js', 'text/javascript')
        ->appendFile(TEMPLATE_URL . '/admin/system/plugins/knob/jquery.knob.js', 'text/javascript')
        ->appendFile(TEMPLATE_URL . '/admin/system/plugins/daterangepicker/daterangepicker.js', 'text/javascript')
        ->appendFile(TEMPLATE_URL . '/admin/system/plugins/datepicker/bootstrap-datepicker.js', 'text/javascript')
        ->appendFile(TEMPLATE_URL . '/admin/system/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js', 'text/javascript')
        ->appendFile(TEMPLATE_URL . '/admin/system/plugins/iCheck/icheck.min.js', 'text/javascript')
        ->appendFile(TEMPLATE_URL . '/admin/system/plugins/slimScroll/jquery.slimscroll.min.js', 'text/javascript')
        ->appendFile(TEMPLATE_URL . '/admin/system/dist/js/app.min.js', 'text/javascript')
        ->appendFile(TEMPLATE_URL . '/admin/system/dist/js/pages/dashboard.js', 'text/javascript')
        ->appendFile(TEMPLATE_URL . '/admin/system/dist/js/demo.js', 'text/javascript')
        ->appendFile(TEMPLATE_URL . '/admin/system/js/jquery-ui.min.js', 'text/javascript')
        ->appendFile(TEMPLATE_URL . '/admin/system/js/raphael-min.js', 'text/javascript')
        ->appendFile(TEMPLATE_URL . '/admin/system/js/fastclick.min.js', 'text/javascript');
?>